version: '3.3 '

services:
  car-api:
    container_name: car-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3004
    volumes:
      - ./:/usr/src/car-api
    working_dir: /usr/src/car-api
    networks:
      - monorepo-network

    command: bash -c "npm install && npm run build && npm run start:prod"

  car-batch:
    container_name: car-batch
    restart: always
    image: node:20.10.0
    ports:
      - 4002:3009
    volumes:
      - ./:/usr/src/car-api
    working_dir: /usr/src/car-api
    networks:
      - monorepo-network

    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
